AWSTemplateFormatVersion: 2010-09-09
Description: "The template used to create an ECS Cluster from the ECS Console."
Parameters:
  ECSClusterName:
    Description: Name of ECS cluster we are making
    Type: String

  ECRName:
    Description: Name of ECR, where we are pushing our docker image.
    Type: String  
    
Resources:
   MyPublicRepositry:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: !Ref ECRName
   ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ECSClusterName
      CapacityProviders:
        - FARGATE
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      
