AWSTemplateFormatVersion: 2010-09-09
Description: The template used to create an ECS Service from the ECS Console.
Parameters:
  ECSClusterName:
    Type: String
    Default: sidcluster22
  SecurityGroupName:
    Type: CommaDelimitedList
    Default: sidgrp
  # SubnetIDs:
  #   Type: CommaDelimitedList
  #   Default: subnet-09bf02e63955300e1,subnet-09281262d4fb8facf,subnet-0206e689986e8cd5d
  # VpcID:
  #   Type: String
  #   Default: vpc-0c500a6e56e6939a8
  LoadBalancerName:
    Type: String
    Default: sidlb2
Resources:
  MyTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: sid-task-definition
      Cpu: 1024
      Memory: 3072
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: contsid     
          Image: public.ecr.aws/v6d4w2e8/siddhantrepo2:latest
          PortMappings:
            - ContainerPort: 5000
              Protocol: tcp    
      RequiresCompatibilities:
        - FARGATE
  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: sidcluster22
      TaskDefinition: !Ref MyTaskDefinition
      LaunchType: FARGATE
      ServiceName: sidservice2
      SchedulingStrategy: REPLICA
      DesiredCount: 3
      LoadBalancers:
        - ContainerName: contsid
          ContainerPort: 5000
          LoadBalancerName: !Ref 'AWS::NoValue'
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref SecurityGroup
          Subnets:
           - Fn::ImportValue: PublicSubnet1
           - Fn::ImportValue: PublicSubnet2
           - Fn::ImportValue: PublicSubnet3
      PlatformVersion: LATEST
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      Tags: []
      EnableECSManagedTags: true
    DependsOn:
      - Listener
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: for ecs cluster
      GroupName: sidgrp
      VpcId:
        Fn::ImportValue: VPC
      SecurityGroupIngress:
        - FromPort: -1
          ToPort: -1
          IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
        - FromPort: -1
          ToPort: -1
          IpProtocol: '-1'
          CidrIpv6: '::/0'
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Type: application
      Name: sidlb2
      SecurityGroups:
        - !Ref SecurityGroup
      Subnets:
        - Fn::ImportValue: PublicSubnet1
        - Fn::ImportValue: PublicSubnet2
        - Fn::ImportValue: PublicSubnet3
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckPath: /
      Name: sidtrgt2
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckProtocol: HTTP
      VpcId:
        Fn::ImportValue: VPC
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
  

